# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 609eb9ea35a9501e0bceba76f152cf7bec38f9bc025d8d071cdbf796bcfa5e348fd007832d9ac2e56601aa7228a23052a357a1d09cab20a5934bffdeee528689

test:
  secret_key_base: 65eb84337c180f72555920cd0c9a9db64735198d7b45b648e23b181651a4f371928beba40a88baa301d0bbc216eac91d5d9bd327ee4a7c3472f12b3436d1f300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
